# Dataset parameters
seed: 0                 # Random seed for reproducibility
batch_size: 10          # Number of (img1, img2, flow, density) tuples per batch
include_images: true    # Whether to include images in the dataset
loop: true              # Whether to loop the dataset (true because there's only one pair)
randomize: false        # Whether to randomize the order of the batches

# Image parameters
image_shape: [256, 256] # Shape of the images

# Flows files
scheduler_files: docs/examples/npy
scheduler_class: ".npy"
