# Dataset parameters
seed: 0 # Random seed for reproducibility
batch_size: 1 # Number of (img1, img2, flow) tuples per batch
flow_fields_per_batch: 1 # Number of flow fields used for each batch
batches_per_flow_batch: 1 # Number of batches of (imgs1, imgs2, flows) tuples per flow batch

# Image generation parameters
image_shape: [256, 256] # Shape of the images to be generated
dt: 1 # Time step between images
seeding_density_range: [0.03, 0.04] # Range of density of particles in the images
p_hide_img1: 0.0001 # Probability of hiding particles in the first image
p_hide_img2: 0.0001 # Probability of hiding particles in the second image
diameter_ranges: [[1.5, 2.5]]  # Diameter of particles in pixels
diameter_var: 0.03 # Variance of the diameter of particles
intensity_ranges: [[150, 230]] # Range of intensity values for the particles
intensity_var: 0.01 # Variance of the intensity of particles
rho_ranges: [[-0.1, 0.1]] # Correlation coefficients for the particles (similarity)
rho_var: 0.1 # Variance of the correlation coefficients for the particles
noise_uniform: 0.001 # Maximum amplitude of the uniform noise to add.
noise_gaussian_mean: 0.001 # Mean of the Gaussian noise to add
noise_gaussian_std: 0.000001 # Standard deviation of the Gaussian noise to add

# Flow generation parameters
velocities_per_pixel: 1.0 # Number of velocities per pixel
resolution: 1 # Pixels per unit length
# In this dataset, the velocities are already in pixels (they are displacements)
# so we set the resolution and the dt to 1, they shouldn't be modified.
# Same goes for image_shape and flow_field_size

# -- Flow parameters --
# Size of the flow field in normalized units. It can be meters or others,
# but need to be consistent in the other dependent settings.
flow_field_size: [256, 256]
img_offset: [0, 0] # Offset of the area captured in the images in normalized units
# Speeds bounds in the flow field, used to have particles covering the images
min_speed_x: 0 # Minimum speed in the x direction
max_speed_x: 0 # Maximum speed in the x direction
min_speed_y: 0 # Minimum speed in the y direction
max_speed_y: 0 # Maximum speed in the y direction
# Units of the output flow field. Can be "measure units per second" or "pixels"
output_units: "pixels"
# Flows files
file_list:
  - /shared/fluids/fluids-estimation/piv_dataset_final/train/cylinder_full
scheduler_class: ".mat"
